name = "Otterman-Minecraft-1.20.X"
author = "ssamjh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19d55361d611fc37142e8deb757a9d932fe3ca6239337128a775c211e599707a"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
