name = "Otterman-Minecraft-1.20.X"
author = "ssamjh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b9575813d31a4d0af33c91ea117f8b5cfde4e13d82e88ccc55d8c716bfc2bb9"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
