name = "Otterman-Minecraft-1.20.X"
author = "ssamjh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3820d4b38e4faa48ade0cb52276f9123dfa9bfa35b853ab2da25f0219aeb8477"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
