name = "Otterman-Minecraft-1.20.X"
author = "ssamjh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf5830c6c7c1873949d26d9b209e184294503d79e9a95ab4e383ba43d5bb9623"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
