name = "Otterman-Minecraft-1.20.X"
author = "ssamjh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b33a0a27cddf82f486e5456983d49242f434c033db6a2e2a4d92b5fec56c7423"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
