name = "Otterman-Minecraft-1.20.X"
author = "ssamjh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bff2818313e5fce960aac0d85be67d5fc5490b92caf93001f9d1f7ea76042574"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
