name = "Otterman-Minecraft-1.20.X"
author = "ssamjh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c67ff08e846319f37f79f50bc5e9e8bbce05b0c401a13fc48bd1cc3e55e6e16b"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
