name = "Otterman-Minecraft-1.20.X"
author = "ssamjh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25b5f531b4a2dd1a14924e1994859af65814bbe12a8aa533e04b5aa526d3106f"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
