name = "Otterman-Minecraft-1.20.X"
author = "ssamjh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb49fd2849f945a05868ba8c9a516d7555ff3c8acddaf5a6527e48973b55f4cd"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
