name = "Otterman-Minecraft-1.20.X"
author = "ssamjh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f40af52a6f7a394acb893d21dc15ca69c17f8f6410c89de140ed9c15b241144"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
