name = "Otterman-Minecraft-1.20.X"
author = "ssamjh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48b8c9ae3c474d0b31280bd408e2741e220f1eee762b5a64a7c1cb2c95fc89cf"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
