name = "Otterman-Minecraft-1.20.X"
author = "ssamjh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f99e4dbfd89f6b760bc2b43a9f53bfd5010f457b5ccbad49a700bb97ff51dcd4"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
