name = "Otterman-Minecraft-1.20.X"
author = "ssamjh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7870e74e44485d4a54fb039d08effdfd86cb2b6d5cc5e166afef49b212c72701"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
