name = "Otterman-Minecraft-1.20.X"
author = "ssamjh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aef2fe2d6086d3b96ece1777fce315b7b397bab331a7fe05436b86cb578ba5d1"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
