name = "Otterman-Minecraft-1.20.X"
author = "ssamjh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a41c5c25f55ffbe6c64d3a23e10576b70cb1a8b042e6a32dedd12ee61c0b7e5"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
